version: '3'
services:
  backend: 
    image: 'atascados-api'
    container_name: 'atascados-api'
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: '.docker/Dockerfile'
    ports:
      - 3000:3000
    env_file:
      - .env.development
    volumes:
      - ./:/usr/src/app
    networks:
      atascados-network:
  mongo:
    image: 'mongo:latest'
    container_name: 'atascados-db'
    restart: always
    platform: linux/amd64
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - db:/data/db
    networks:
      atascados-network:

networks:
  atascados-network:
    driver: bridge

volumes:
  db:
    driver: local
